sudo: required

services:
  - docker

before_install:
  - docker build -t naspuka/docker-react -f Dockerfile.dev .

script:
  - docker run naspuka/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-1"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-east-1-148344494599"
#   bucket_path: "docker"
#   on: 
#     branch: master